apiVersion: v1
kind: Secret
metadata:
  name: lakehouse-oidc-credentials
  namespace: lakehouse
  labels:
    app.kubernetes.io/part-of: lakehouse
    app.kubernetes.io/component: security-oidc
type: Opaque
stringData:
  OIDC_DISCOVERY_URL: "http://keycloak.lakehouse.svc.cluster.local:8080/realms/lakehouse/.well-known/openid-configuration"
  OIDC_ISSUER_URL: "http://keycloak.lakehouse.svc.cluster.local:8080/realms/lakehouse"
  TRINO_CLIENT_ID: "trino"
  TRINO_CLIENT_SECRET: "trino-client-secret-12345"
  MINIO_CLIENT_ID: "minio"
  MINIO_CLIENT_SECRET: "minio-client-secret-12345"

