name: 'lakehouse_dbt'
version: '1.0.0'
config-version: 2

profile: 'lakehouse_trino'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  lakehouse_dbt:
    silver:
      +schema: silver
      +materialized: table
    gold:
      +schema: gold
      +materialized: table

